-- MySQL Script generated by MySQL Workbench
-- 08/18/15 17:29:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema trabalho_dba
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trabalho_dba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trabalho_dba` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `trabalho_dba` ;

-- -----------------------------------------------------
-- Table `trabalho_dba`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_dba`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nome_cliente` VARCHAR(45) NOT NULL COMMENT '',
  `cpf_cliente` VARCHAR(45) NOT NULL COMMENT '',
  `tel_cliente` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_cliente`)  COMMENT '',
  UNIQUE INDEX `id_cliente_UNIQUE` (`id_cliente` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trabalho_dba`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trabalho_dba`.`produto` (
  `id_produto` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `codbarra_produto` VARCHAR(45) NOT NULL COMMENT '',
  `nome_produto` VARCHAR(45) NOT NULL COMMENT '',
  `marca_produto` VARCHAR(45) NULL COMMENT '',
  `tipo_produto` VARCHAR(45) NULL COMMENT '',
  `unidade_produto` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_produto`)  COMMENT '',
  UNIQUE INDEX `id_produto_UNIQUE` (`id_produto` ASC)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
